name: Dependabot Approve & Auto-Merge
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      -
        name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      -
        name: Output Metadata
        run: |
          echo "${{ steps.metadata.outputs.dependency-names }}"
          echo "${{ steps.metadata.outputs.dependency-type }}"
          echo "${{ steps.metadata.outputs.update-type }}"
      -
        name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Enable auto-merge for Dependabot PRs
        # if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
